### ISSUE TITLE
feedback on afrianska

### ISSUE THREAD

**Issue by maxqwer** [sycale/afrianska#1]
1) 123.scss - choose better (self-documented) names for the files.
2) create separated directory for the assets (such as images, which currently placed in the root directory)
3) You've added logs file to .gitignore which is good, but you didn't remove it from repo. Never push any auto generated files to the repo, nobody need them since it all can be reproduced locally
4) remove all unused code from repository (e.g. task2.js, main.js, main.css, etc.)
5) webpack.config.js contains information required to build your project -- it's should present in the repo
6) Use BEM, https://ru.bem.info/methodology/quick-start - use blocks, elements and modificators appropriately. I would recommend to use [Harry Roberts naming convention](https://ru.wikipedia.org/wiki/%D0%91%D0%AD%D0%9C#%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0_%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%91%D0%AD%D0%9C-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2_%D0%BE%D1%82_%D0%93%D0%B0%D1%80%D1%80%D0%B8_%D0%A0%D0%BE%D0%B1%D0%B5%D1%80%D1%82%D1%81%D0%B0) for modificators. But it's up to you which one would you prefer, but obviously it should be consistent throughout the project 
@sycale

**Comment by sycale** [comment]
Khorosho!!!
